### ISSUE TITLE
Crater logo and all the copyrighted thingy.

### ISSUE THREAD

**Issue by mlikr** [MuhdSaifulnizam15/tuition-management-system#13]
Macam mana nak ubah logo crater tu eh? And then link dekat "Powered by" to boleh link to either one of us punya github page. Hehe.

**Comment by MuhdSaifulnizam15** [comment]
link href boleh ubah dekat file ni _resources/js/views/layouts/partials/TheSiteFooter.vue_

logo tu pun boleh ubah image dlm file sidebar. Cari file sidebar dlm folder ni _resources/js/views/layouts/partials/_ atau _resources/js/views/layouts_

**Comment by mlikr** [comment]
Alright nanti aku cek kk. Thanks saiful !!

**Comment by MuhdSaifulnizam15** [comment]
![image](https://user-images.githubusercontent.com/57882573/99845994-845f2b00-2bb0-11eb-8a3a-62ba1f964192.png)
Blur/pixelated logo, need higher resolution image

**Comment by mlikr** [comment]
Amended, please check.

**Comment by MuhdSaifulnizam15** [comment]
Amendment verified. Issue closed
