### ISSUE TITLE
Dashboard: Change recent estimates to students list

### ISSUE THREAD

**Issue by mlikr** [MuhdSaifulnizam15/tuition-management-system#14]
Saiful, aku tak faham code ni :(

```
<table-component
            ref="est_table"
            :data="getRecentEstimates"
            :show-filter="false"
            table-class="table"
          >

```
Aku search jugak throughout repo, aku carik ref tu dekat :data tu tapi cam aku tak faham dia tarik data dari mana..

**Comment by MuhdSaifulnizam15** [comment]
getRecentEstimates ada getter method. Bukak code asal crater, tgk dlm folder store/modules/dashboard/getter.js. Dlm repo ni aku excludealso state management for estimates. Yg ni biar aku buat sebab value yg nak display kat dashboard dah call dekat api, cuma x display lagi dekat frontend. Aku x sangka integration frontend amik masa dua kali ganda lagi lama drpd buat api

**Comment by mlikr** [comment]
Nanti kerja aku, aku letak placeholder je tau. Nanti kau masukkan apa yang perlu kk? Aku dah siapkan dashboard. Nak gi tengok views yang lain. 😙😙

--
ABDUL MALIK RIDHWAN BIN ADAM MALEK
21, Student
Tel No.: 014 - 206 2064
