### ISSUE TITLE
StudentController.php

### ISSUE THREAD

**Issue by mlikr** [MuhdSaifulnizam15/tuition-management-system#9]
![SQLSERVE](https://user-images.githubusercontent.com/73153159/99358833-0b7a7d80-28e9-11eb-8c86-081e8bdb851e.png)

![SQLSERVE2](https://user-images.githubusercontent.com/73153159/99358883-23520180-28e9-11eb-95e2-cd160907b27e.png)

Saifuuuuuuuuul

**Comment by MuhdSaifulnizam15** [comment]
Issue resolved. Please verify. Pull from branch development

**Comment by mlikr** [comment]
Problem still occur, already git pull :(

**Comment by MuhdSaifulnizam15** [comment]
Please run fresh migration.

**Comment by mlikr** [comment]
Masih sama :((
![full_name1](https://user-images.githubusercontent.com/73153159/99741530-59230000-2b0c-11eb-8c5c-d62a1931dc93.png)

![full_name2](https://user-images.githubusercontent.com/73153159/99741527-56c0a600-2b0c-11eb-9f8f-17ecc346a3b3.png)

**Comment by MuhdSaifulnizam15** [comment]
tengok table students dekat phpmyadmin, ada x field full_name dlm table tu

**Comment by MuhdSaifulnizam15** [comment]
most likely sebab x de field full_name tu. Kalau x de field tu, tgk _create_table_students_ file dlm folder _database/migrations_ ada x line ni `$table->string('full_name')`

**Comment by mlikr** [comment]
Hmm line tu ada.... Tapi itulah, kenapa tak boleh eh..

**Comment by MuhdSaifulnizam15** [comment]
pull branch develop, run balik migration. Maybe issue with default string length

**Comment by mlikr** [comment]
Balik Miri ahad ni aku cuba, takleh deploy kat macbook aku. Sed.
